baseURL = "https://questkislovodsk.ru/"
publishDir ="docs"
languageCode = "ru"
title = "Квест для всей семьи"
theme = "istudio"
[params]
  name = "Questo"
  address = "проспект Победы, 6"
  timeWork = "10:00 - 22:00"
